ADD, Coloring to hooks messages
lnxpy/cookiecutter-pyaction pull request #16
Opened 2023-08-10 17:10 UTC by Farhaduneci

This PR would add a coloring module to the hooks directory containing `cprint` function and the `Text` data-class which can be used to apply various styling on any texts.

Example usages can be seen on the hooks themselves as they are being updated to use these new utilities.

2023-08-10 17:11 UTC, Farhaduneci commented
Closes #6

2023-08-11 11:26 UTC, lnxpy approved these changes

2023-08-17 11:06 UTC, lnxpy requested changes

2023-09-07 14:17 UTC, lnxpy commented
Since this pr doesn't work and it's caused some conflicts, I keep it closed for now.

2023-09-07 14:17 UTC, closed without merging